/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yoyo;

/**
 *
 * @author Eow
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        login_lbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JTextField();
        login_btn = new javax.swing.JButton();
        register_btn = new javax.swing.JButton();
        staff_btn = new javax.swing.JButton();
        staff_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        right.setBackground(new java.awt.Color(0, 0, 0));
        right.setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(right);
        right.setBounds(0, 0, 400, 500);

        login_lbl.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 36)); // NOI18N
        login_lbl.setText("Login");
        jPanel1.add(login_lbl);
        login_lbl.setBounds(540, 40, 100, 40);

        email_lbl.setText("Email:");
        jPanel1.add(email_lbl);
        email_lbl.setBounds(490, 120, 50, 14);

        password_lbl.setText("Password:");
        jPanel1.add(password_lbl);
        password_lbl.setBounds(470, 170, 80, 14);
        jPanel1.add(email_txt);
        email_txt.setBounds(590, 120, 90, 18);
        jPanel1.add(password_txt);
        password_txt.setBounds(590, 170, 90, 18);

        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel1.add(login_btn);
        login_btn.setBounds(480, 260, 64, 24);

        register_btn.setText("Register");
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });
        jPanel1.add(register_btn);
        register_btn.setBounds(610, 260, 78, 24);

        staff_btn.setText("Login here");
        staff_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_btnActionPerformed(evt);
            }
        });
        jPanel1.add(staff_btn);
        staff_btn.setBounds(680, 460, 100, 24);

        staff_lbl.setText("Already a staff?");
        jPanel1.add(staff_lbl);
        staff_lbl.setBounds(580, 470, 100, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
        RegisterUI RegisterFrame = new RegisterUI();
        RegisterFrame.setVisible(true);
        RegisterFrame.pack();
        RegisterFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_register_btnActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        String userEmail = email_txt.getText();
        String userPassword = password_txt.getText();
        if (Authentication.authenticateUser(userEmail, userPassword)) {
            // If authentication is successful, navigate to the MainMenu
            MainMenuUI mainMenu = new MainMenuUI();
            mainMenu.setVisible(true);
            mainMenu.pack();
            mainMenu.setLocationRelativeTo(null);
            this.dispose(); // Close the Login frame
        } else {
            // If authentication fails, display an error message or handle it accordingly
            System.out.println("Invalid email or password. Please try again.");
        }
    
        
    
    }//GEN-LAST:event_login_btnActionPerformed

    private void staff_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_btnActionPerformed
        EmployeeLoginUI EmployeeLoginFrame = new EmployeeLoginUI();
        EmployeeLoginFrame.setVisible(true);
        EmployeeLoginFrame.pack();
        EmployeeLoginFrame.setLocationRelativeTo(null);
        this.dispose();      
    }//GEN-LAST:event_staff_btnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel login_lbl;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JTextField password_txt;
    private javax.swing.JButton register_btn;
    private javax.swing.JPanel right;
    private javax.swing.JButton staff_btn;
    private javax.swing.JLabel staff_lbl;
    // End of variables declaration//GEN-END:variables
}
